Models/Customers.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ControlPanel.Models
{
    [Table("Customers")]
    public class Customers
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
    }
}

Controllers/CustomerController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ControlPanel.Controllers
{
    public class CustomerController : Controller
    {
        private readonly Models.VPCustomersContext CustomersContext;

        public CustomerController(Models.VPCustomersContext _context)
        {
            CustomersContext = _context;
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 2)
                {
                    try
                    {
                        return View(await (from us in CustomersContext.Customer
                                           where us.id == id
                                           select us).FirstAsync());
                    }
                    catch (Exception ex)
                    {
                        TempData["ActionError"] = ex.Message;

                        return RedirectToAction("Customers", "Home");
                    }
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customers", "Home");
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int _id, string _name, string _website, string _phone1,
            string _phone2, string _address, string _email)
        {
            string _oldname = "";
            try
            {
                var _customer = await (from cust in CustomersContext.Customer
                                       where cust.id == _id
                                       select cust).FirstAsync();

                _oldname = _customer.Name;

                _customer.Name = _name;
                _customer.Website = _website;
                _customer.Phone1 = _phone1;
                _customer.Phone2 = _phone2;
                _customer.Address = _address;
                _customer.Email = _email;

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully edited customer " + _name;

                return RedirectToAction("Customers", "Home");
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error editing customer " + _oldname + " .   " + ex.Message;

                return RedirectToAction("Customers", "Home");
            }

        }

        public async Task<IActionResult> Delete(int id)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 2)
                {
                    try
                    {
                        return View(await (from cust in CustomersContext.Customer
                                           where cust.id == id
                                           select cust).FirstAsync());
                    }
                    catch (Exception ex)
                    {
                        TempData["ActionError"] = ex.Message;

                        return RedirectToAction("Customers", "Home");
                    }
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customers", "Home");
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int _id, string _name)
        {
            try
            {
                //
                // Remove customer's details first
                //
                var _custDetails = from t0 in CustomersContext.CustomerDetails
                                   where t0.CustomerId == _id
                                   select t0;

                foreach (var _element in _custDetails)
                {
                    CustomersContext.CustomerDetails.Remove(_element);
                }

                await CustomersContext.SaveChangesAsync();
                //
                // Remove customer's payments details now
                //
                var _custPayment = from t0 in CustomersContext.Payment
                                   where t0.CustomerId == _id
                                   select t0;

                foreach (var _element in _custPayment)
                {
                    CustomersContext.Payment.Remove(_element);
                }

                await CustomersContext.SaveChangesAsync();
                //
                // Remove customer last
                //
                CustomersContext.Customer.Remove(await (from cust in CustomersContext.Customer
                                                        where cust.id == _id
                                                        select cust).FirstAsync()
                                                );

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully removed customer " + _name;

                return RedirectToAction("Customers", "Home");
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error removing customer " + _name + " .   " + ex.Message;

                return RedirectToAction("Customers", "Home");
            }
        }

        public IActionResult Add()
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 3)
                {
                    return View();
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customers", "Home");
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(string _name, string _website, string _phone1,
            string _phone2, string _address, string _email)
        {
            try
            {
                await CustomersContext.Customer.AddAsync(new Models.Customers()
                {
                    Name = _name,
                    Website = _website,
                    Phone1 = _phone1,
                    Phone2 = _phone2,
                    Address = _address,
                    Email = _email
                });

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully added customer " + _name;

                return RedirectToAction("Customers", "Home");
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error adding customer " + _name + " .   " + ex.Message;

                return RedirectToAction("Customers", "Home");
            }
        }
    }
}

Controllers/PaymentsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ControlPanel.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly Models.VPCustomersContext CustomersContext;

        public PaymentsController(Models.VPCustomersContext _context)
        {
            CustomersContext = _context;
        }

        public async Task<IActionResult> Customer(int id)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                try
                {
                    var _customerPay = await (from t0 in CustomersContext.Payment
                                              where t0.CustomerId == id
                                              select t0).ToListAsync();

                    var _customer = await (from t0 in CustomersContext.Customer
                                           where t0.id == id
                                           select t0).FirstAsync();

                    ViewData["Title"] = _customer.Name + "'s Payment Details";
                    ViewData["Name"] = _customer.Name;
                    ViewData["CustId"] = _customer.id;

                    if (_customer.Website.Length > 0)
                    {
                        ViewData["Website"] = _customer.Website;
                    }

                    return View(_customerPay);
                }
                catch (Exception ex)
                {
                    TempData["ActionError"] = ex.Message;

                    return RedirectToAction("Customers", "Home");
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Add(int id)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 3)
                {
                    try
                    {
                        return View(id);
                    }
                    catch (Exception ex)
                    {
                        TempData["ActionError"] = ex.Message;
                        return RedirectToAction("Customer", new { id = id });
                    }
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customer", new { id = id });
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(int _custId, string _type, string _date, double _amount)
        {
            try
            {
                var _LastLine = await (from t0 in CustomersContext.Payment
                                       where t0.CustomerId == _custId
                                       select t0.LineNo).LastOrDefaultAsync();

                await CustomersContext.Payment.AddAsync(new Models.Payments
                {
                    CustomerId = _custId,
                    LineNo = _LastLine + 1,
                    Type = _type.Encrypt(),
                    Date = _date.Encrypt(),
                    Amount = _amount
                });

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully added customer's payments details.";

                return RedirectToAction("Customer", new { id = _custId });
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error adding customer's payments details.   " + ex.InnerException;

                return RedirectToAction("Customer", new { id = _custId });
            }
        }

        public async Task<IActionResult> Edit(int id, int LineNo)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 2)
                {
                    try
                    {
                        ViewData["Name"] = await (from t0 in CustomersContext.Customer
                                                  where t0.id == id
                                                  select t0.Name).FirstAsync();

                        return View(await (from t0 in CustomersContext.Payment
                                           where t0.CustomerId == id && t0.LineNo == LineNo
                                           select t0).FirstAsync());
                    }
                    catch (Exception ex)
                    {
                        TempData["ActionError"] = ex.Message;

                        return RedirectToAction("Customer", new { id = id });
                    }
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customer", new { id = id });
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int _id, int _custId, string _type = "",
            string _date = "", double _amount = 0)
        {
            try
            {
                var _custDetailLine = await (from t0 in CustomersContext.Payment
                                             where t0.id == _id
                                             select t0).FirstAsync();

                _custDetailLine.Type = _type.Encrypt();
                _custDetailLine.Date = _date.Encrypt();
                _custDetailLine.Amount = _amount;

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully edited customer's payments details.";

                return RedirectToAction("Customer", new { id = _custId });
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error editing customer's payments details.   " + ex.InnerException;

                return RedirectToAction("Customer", new { id = _custId });
            }
        }

        public async Task<IActionResult> Delete(int id, int LineNo)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 2)
                {
                    try
                    {
                        await (from t0 in CustomersContext.Payment
                               where t0.CustomerId == id && t0.LineNo == LineNo
                               select t0).FirstAsync();

                        ViewData["id"] = id;

                        return View(LineNo);
                    }
                    catch (Exception ex)
                    {
                        TempData["ActionError"] = ex.Message;

                        return RedirectToAction("Customer", new { id = id });
                    }
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customer", new { id = id });
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int _custId, int? _lineNo)
        {
            try
            {
                CustomersContext.Payment.Remove(
                    await (from t0 in CustomersContext.Payment
                           where t0.CustomerId == _custId && t0.LineNo == _lineNo
                           select t0).FirstAsync()
                );

                await CustomersContext.SaveChangesAsync();

                var _custPaymentsDetails = await (from t0 in CustomersContext.Payment
                                                  where t0.CustomerId == _custId && t0.LineNo > _lineNo
                                                  select t0).ToListAsync();

                foreach (var _element in _custPaymentsDetails)
                {
                    _element.LineNo -= 1;
                }

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully removed customer's payment details.";

                return RedirectToAction("Customer", new { id = _custId });
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error removing customer's payment details.   " + ex.InnerException;

                return RedirectToAction("Customer", new { id = _custId });
            }
        }
    }
}

Views/Home/Customers.cshtml
@model IEnumerable<ControlPanel.Models.Customers>

@{
    ViewData["Title"] = "All Customers";
}

<!-- Alert Messages -->

@if ((bool)TempData.ContainsKey("ActionError"))
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>@TempData["ActionError"]</strong>
    </div>
}
else if ((bool)TempData.ContainsKey("ActionSuccess"))
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>@TempData["ActionSuccess"]</strong>
    </div>
}
else if ((bool)TempData.ContainsKey("Unprivileged"))
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Seems like with your current Rank(@TempData["Unprivileged"]) you are not able to perform this action</strong>
    </div>
}

<!-- Customers Table -->
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Website</th>
                <th>Phone 1</th>
                <th>Phone 2</th>
                <th>Address</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var _cust in Model)
        {
            <tr>
                <td>@_cust.Name</td>
                <td>
                    <a href="http://@_cust.Website" target="_blank">@_cust.Website</a>
                </td>
                <td>@_cust.Phone1</td>
                <td>@_cust.Phone2</td>
                <td>@_cust.Address</td>
                <td>@_cust.Email</td>
                <td>
                    <a class="btn btn-primary" role="button" title="Customer's Details"
                        asp-action="Customer" asp-controller="CustomerDetails" asp-route-id="@_cust.id">
                        <span class="glyphicon glyphicon-align-justify" aria-hidden="true" />
                    </a>

                    <a class="btn btn-primary" role="button" title="Customer's Payments Details"
                        asp-action="Customer" asp-controller="Payments" asp-route-id="@_cust.id">
                        <span class="glyphicon glyphicon-euro" aria-hidden="true" />
                    </a>

                    <a class="btn btn-primary" role="button" title="Edit Customer"
                        asp-action="Edit" asp-controller="Customer" asp-route-id="@_cust.id">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true" />
                    </a>

                    <a class="btn btn-danger" role="button" title="Remove Customer"
                        asp-action="Delete" asp-controller="Customer" asp-route-id="@_cust.id">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true" />
                    </a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

<a class="btn btn-primary" role="button" asp-action="Add" asp-controller="Customer" title="Add Customer">
    Add Customer
</a>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Visual Pivot Control Panel";
}

<h1>Visual Pivot Control Panel</h1>

@{
    if ((bool)TempData.ContainsKey("LogFail"))
    {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Log In Failed for user @TempData["LogFail"]</strong>
        </div>

        TempData.Remove("LogFail");
    }
    else if ((bool)TempData.ContainsKey("ValidateException"))
    {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>@TempData["ValidateException"]</strong>
        </div>

        TempData.Remove("ValidateException");
    }
    else if ((bool)TempData.ContainsKey("SessionExpired"))
    {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Seems like you are not logged in or your Session has expired</strong> Please Log In...
        </div>

        TempData.Remove("SessionExpired");
    }
    else if ((bool)TempData.ContainsKey("NoUserName"))
    {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>User Name is missing. Please state who are you</strong>
        </div>

        TempData.Remove("NoUserName");
    }

    if ((bool)TempData.ContainsKey("AdminCreated"))
    {
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>User admin was missing and was created with Password "1234". Please consider changing Password ASAP!</strong>
        </div>

        TempData.Remove("AdminCreated");
    }
}

<form asp-action="Validate" autocomplete="off">
    <div class="form-group">
        <label for="name" class="control-label">User Name</label>
        <input type="text" name="_name" class="form-control" placeholder="User's Name" />
    </div>

    <div class="form-group">
        <label for="pass">Password</label>
        <input type="password" name="_pass" class="form-control" placeholder="Password" />
    </div>
    <button type="submit" class="btn btn-primary">Log In</button>
</form>