Models/Customers.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ControlPanel.Models
{
    [Table("Customers")]
    public class Customers
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Website { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
    }
}

Controllers/CustomerController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ControlPanel.Controllers
{
    public class CustomerController : Controller
    {
        private readonly Models.VPCustomersContext CustomersContext;

        public CustomerController(Models.VPCustomersContext _context)
        {
            CustomersContext = _context;
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 2)
                {
                    try
                    {
                        return View(await (from us in CustomersContext.Customer
                                           where us.id == id
                                           select us).FirstAsync());
                    }
                    catch (Exception ex)
                    {
                        TempData["ActionError"] = ex.Message;

                        return RedirectToAction("Customers", "Home");
                    }
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customers", "Home");
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int _id, string _name, string _website, string _phone1,
            string _phone2, string _address, string _email)
        {
            string _oldname = "";
            try
            {
                var _customer = await (from cust in CustomersContext.Customer
                                       where cust.id == _id
                                       select cust).FirstAsync();

                _oldname = _customer.Name;

                _customer.Name = _name;
                _customer.Website = _website;
                _customer.Phone1 = _phone1;
                _customer.Phone2 = _phone2;
                _customer.Address = _address;
                _customer.Email = _email;

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully edited customer " + _name;

                return RedirectToAction("Customers", "Home");
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error editing customer " + _oldname + " .   " + ex.Message;

                return RedirectToAction("Customers", "Home");
            }

        }

        public async Task<IActionResult> Delete(int id)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 2)
                {
                    try
                    {
                        return View(await (from cust in CustomersContext.Customer
                                           where cust.id == id
                                           select cust).FirstAsync());
                    }
                    catch (Exception ex)
                    {
                        TempData["ActionError"] = ex.Message;

                        return RedirectToAction("Customers", "Home");
                    }
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customers", "Home");
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int _id, string _name)
        {
            try
            {
                //
                // Remove customer's details first
                //
                var _custDetails = from t0 in CustomersContext.CustomerDetails
                                   where t0.CustomerId == _id
                                   select t0;

                foreach (var _element in _custDetails)
                {
                    CustomersContext.CustomerDetails.Remove(_element);
                }

                await CustomersContext.SaveChangesAsync();
                //
                // Remove customer's payments details now
                //
                var _custPayment = from t0 in CustomersContext.Payment
                                   where t0.CustomerId == _id
                                   select t0;

                foreach (var _element in _custPayment)
                {
                    CustomersContext.Payment.Remove(_element);
                }

                await CustomersContext.SaveChangesAsync();
                //
                // Remove customer last
                //
                CustomersContext.Customer.Remove(await (from cust in CustomersContext.Customer
                                                        where cust.id == _id
                                                        select cust).FirstAsync()
                                                );

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully removed customer " + _name;

                return RedirectToAction("Customers", "Home");
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error removing customer " + _name + " .   " + ex.Message;

                return RedirectToAction("Customers", "Home");
            }
        }

        public IActionResult Add()
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 3)
                {
                    return View();
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customers", "Home");
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(string _name, string _website, string _phone1,
            string _phone2, string _address, string _email)
        {
            try
            {
                await CustomersContext.Customer.AddAsync(new Models.Customers()
                {
                    Name = _name,
                    Website = _website,
                    Phone1 = _phone1,
                    Phone2 = _phone2,
                    Address = _address,
                    Email = _email
                });

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully added customer " + _name;

                return RedirectToAction("Customers", "Home");
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error adding customer " + _name + " .   " + ex.Message;

                return RedirectToAction("Customers", "Home");
            }
        }
    }
}

Controllers/CustomerDetailsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ControlPanel.Controllers
{
    public class CustomerDetailsController : Controller
    {
        private readonly Models.VPCustomersContext CustomersContext;

        public CustomerDetailsController(Models.VPCustomersContext _context)
        {
            CustomersContext = _context;
        }

        public async Task<IActionResult> Customer(int id)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                try
                {
                    var _customerDetails = await (from t0 in CustomersContext.CustomerDetails
                                                  where t0.CustomerId == id
                                                  select t0).ToListAsync();

                    var _customer = await (from t0 in CustomersContext.Customer
                                           where t0.id == id
                                           select t0).FirstAsync();

                    ViewData["Title"] = _customer.Name + "'s Details";
                    ViewData["Name"] = _customer.Name;
                    ViewData["CustId"] = _customer.id;
                    if (_customer.Website.Length > 0)
                    {
                        ViewData["Website"] = _customer.Website;
                    }

                    return View(_customerDetails);
                }
                catch (Exception ex)
                {
                    TempData["ActionError"] = ex.Message;

                    return RedirectToAction("Customers", "Home");
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Add(int id)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 3)
                {
                    try
                    {
                        return View(id);
                    }
                    catch (Exception ex)
                    {
                        TempData["ActionError"] = ex.Message;

                        return RedirectToAction("Customer", new { id = id });
                    }
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customer", new { id = id });
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(int _custId, string _type = "", string _username = "",
            string _password = "")
        {
            try
            {
                var _LastLine = await (from t0 in CustomersContext.CustomerDetails
                                       where t0.CustomerId == _custId
                                       select t0.LineNo).LastOrDefaultAsync();

                await CustomersContext.CustomerDetails.AddAsync(new Models.CustomersDetails
                {
                    CustomerId = _custId,
                    LineNo = _LastLine + 1,
                    Type = _type.Encrypt(),
                    UserName = _username.Encrypt(),
                    Password = _password.Encrypt()
                });

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully added customer's details.";

                return RedirectToAction("Customer", new { id = _custId });
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error adding customer's details.   " + ex.InnerException;
                return RedirectToAction("Customer", new { id = _custId });
            }
        }

        public async Task<IActionResult> Edit(int id, int LineNo)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 2)
                {
                    try
                    {
                        ViewData["Name"] = await (from t0 in CustomersContext.Customer
                                                  where t0.id == id
                                                  select t0.Name).FirstAsync();

                        return View(await (from t0 in CustomersContext.CustomerDetails
                                           where t0.CustomerId == id && t0.LineNo == LineNo
                                           select t0).FirstAsync());
                    }
                    catch (Exception ex)
                    {
                        TempData["ActionError"] = ex.Message;
                        return RedirectToAction("Customer", new { id = id });
                    }
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customer", new { id = id });
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int _id, int _custId, string _type = "", string _username = "",
            string _password = "")
        {
            try
            {
                var _custDetailLine = await (from t0 in CustomersContext.CustomerDetails
                                             where t0.id == _id
                                             select t0).FirstAsync();

                _custDetailLine.Type = _type.Encrypt();
                _custDetailLine.UserName = _username.Encrypt();
                _custDetailLine.Password = _password.Encrypt();

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully edited customer's details.";

                return RedirectToAction("Customer", new { id = _custId });
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error editing customer's details.   " + ex.InnerException;
                return RedirectToAction("Customer", new { id = _custId });
            }
        }

        public async Task<IActionResult> Delete(int id, int LineNo)
        {
            if (HttpContext.Session.GetSession<string>("User") != null)
            {
                if (HttpContext.Session.GetSession<int>("Rank") < 2)
                {
                    try
                    {
                        await (from t0 in CustomersContext.CustomerDetails
                               where t0.CustomerId == id && t0.LineNo == LineNo
                               select t0).FirstAsync();

                        ViewData["id"] = id;

                        return View(LineNo);
                    }
                    catch (Exception ex)
                    {
                        TempData["ActionError"] = ex.Message;

                        return RedirectToAction("Customer", new { id = id });
                    }
                }
                else
                {
                    TempData["Unprivileged"] = HttpContext.Session.GetSession<int>("Rank");
                    return RedirectToAction("Customer", new { id = id });
                }
            }
            else
            {
                TempData["SessionExpired"] = true;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int _custId, int? _lineNo)
        {
            try
            {
                CustomersContext.CustomerDetails.Remove(
                    await (from t0 in CustomersContext.CustomerDetails
                           where t0.CustomerId == _custId && t0.LineNo == _lineNo
                           select t0).FirstAsync()
                );

                await CustomersContext.SaveChangesAsync();

                var _custDetails = await (from t0 in CustomersContext.CustomerDetails
                                          where t0.CustomerId == _custId && t0.LineNo > _lineNo
                                          select t0).ToListAsync();

                foreach (var _element in _custDetails)
                {
                    _element.LineNo -= 1;
                }

                await CustomersContext.SaveChangesAsync();

                TempData["ActionSuccess"] = "Successfully removed customer's details.";

                return RedirectToAction("Customer", new { id = _custId });
            }
            catch (Exception ex)
            {
                TempData["ActionError"] = "Error removing customer's details.   " + ex.InnerException;

                return RedirectToAction("Customer", new { id = _custId });
            }
        }
    }
}

Views/CustomerDetails/Add.cshtml
@{
    ViewData["Title"] = "Add Customer's Details";
}


<form asp-action="Add" method="POST" role="form" name="customerdetails" autocomplete="off"
        onsubmit="return CustDetailsValidate()">
    <legend>Add Customer's Details</legend>

    <div class="form-group">
        <label>Entry Type</label>
        <input type="text" class="form-control" name="_type" placeholder="e.x. Wordpress">
        <div class="alert alert-danger" id="customerdetails_type" style="display: none;"></div>
    </div>

    <div class="form-group">
        <label>User Name</label>
        <input type="text" class="form-control" name="_username">
        <div class="alert alert-danger" id="customerdetails_username" style="display: none;"></div>
    </div>

    <div class="form-group">
        <label>Password</label>
        <input type="text" class="form-control" name="_password">
        <div class="alert alert-danger" id="customerdetails_password" style="display: none;"></div>
    </div>

    <input type="hidden" name="_custId" value="@Model">

    <button type="submit" class="btn btn-primary">Submit</button>

    <a class="btn btn-primary" role="button" asp-action="Customer"
            asp-controller="CustomerDetails" asp-route-id="@Model">
        To Details
    </a>
</form>

Views/CustomerDetails/Customer.cshtml
@model IEnumerable<ControlPanel.Models.CustomersDetails>

@if ((bool)TempData.ContainsKey("ActionError"))
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>@TempData["ActionError"]</strong>
    </div>
}
else if ((bool)TempData.ContainsKey("ActionSuccess"))
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>@TempData["ActionSuccess"]</strong>
    </div>
}
else if ((bool)TempData.ContainsKey("Unprivileged"))
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Seems like with your current Rank(@TempData["Unprivileged"]) you are not able to perform this action</strong>
    </div>
}

<h3>Customer's @ViewData["Name"] Details</h3>
@if ((bool)ViewData.ContainsKey("Website")) {
    <h4>
        You can also check  <a href="http://@ViewData["Website"]" target="_blank">
                                @ViewData["Website"]
                            </a>
    </h4>
}

@if (Model.Any())
{
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Entry Type</th>
                    <th>User Name </th>
                    <th>Password</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var _custDetails in Model)
                {
                    <tr>
                        <td>@_custDetails.Type.Decrypt()</td>
                        <td>@_custDetails.UserName.Decrypt()</td>
                        <td>@_custDetails.Password.Decrypt()</td>
                        <td>
                            <a class="btn btn-primary" role="button" title="Edit Customer's Details"
                                    asp-action="Edit"
                                    asp-route-id="@_custDetails.CustomerId"
                                    asp-route-LineNo="@_custDetails.LineNo">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true" />
                            </a>

                            <a class="btn btn-danger" role="button" title="Remove Customer's Details"
                                    asp-action="Delete"
                                    asp-route-id="@_custDetails.CustomerId"
                                    asp-route-LineNo="@_custDetails.LineNo">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true" />
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

<a class="btn btn-primary" role="button" title="Add Customer's Details"
        asp-action="Add" asp-controller="CustomerDetails" asp-route-id="@ViewData["CustId"]">
    Add Details
</a>

<a class="btn btn-primary" role="button" asp-action="Customers" asp-controller="Home">
    All Customers
</a>

Views/CustomerDetails/Delete.cshtml
@{
    ViewData["Title"] = "Delete Detail No " + Model;
}

<div class="modal show" id="modal-id" style="margin-top:100px;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Really delete customer's detail Line No @Model ?</h4>
            </div>
            <div class="modal-body">
                
                <form asp-action="Delete" method="POST" role="form">
                    <div class="form-group">
                        <input type="hidden" name="_lineNo" value="@Model">
                        <input type="hidden" name="_custId" value="@ViewData["id"]">
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Submit</button>
                    
                    <a asp-action="Customer" asp-controller="CustomerDetails" asp-route-id="@ViewData["id"]">
                        <button type="button" class="btn btn-primary">To Details</button>
                    </a>
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

Views/CustomerDetails/Edit.cshtml
@model ControlPanel.Models.CustomersDetails

@{
    ViewData["Title"] = "Edit Customer's Details";
}


<form asp-action="Edit" method="POST" role="form" name="customerdetails" autocomplete="off"
        onsubmit="return CustDetailsValidate()">
    <legend>Edit Customer's  @ViewData["Name"]  Details</legend>

    <div class="form-group">
        <label>Entry Type</label>
        <input type="text" class="form-control" name="_type" value="@(Model.Type.Decrypt())">
        <div class="alert alert-danger" id="customerdetails_type" style="display: none;"></div>
    </div>

    <div class="form-group">
        <label>User Name</label>
        <input type="text" class="form-control" name="_username" value="@(Model.UserName.Decrypt())">
        <div class="alert alert-danger" id="customerdetails_username" style="display: none;"></div>
    </div>

    <div class="form-group">
        <label>Password</label>
        <input type="text" class="form-control" name="_password" value="@(Model.Password.Decrypt())">
        <div class="alert alert-danger" id="customerdetails_password" style="display: none;"></div>
    </div>

    <input type="hidden" name="_id" value="@(Model.id)">
    <input type="hidden" name="_custId" value="@(Model.CustomerId)">

    <button type="submit" class="btn btn-primary">Submit</button>

    <a asp-action="Customer" asp-route-id="@(Model.CustomerId)">
        <button type="button" class="btn btn-primary">To Details</button>
    </a>
</form>